// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyDB1eFVR_48DHgIBkkkgaO6GprIeE3V5ns',
//     appId: '1:24961272906:web:0358e03e8e41784dcf2ab3',
//     messagingSenderId: '24961272906',
//     projectId: 'climatesolution-48ea6',
//     authDomain: 'climatesolution-48ea6.firebaseapp.com',
//     storageBucket: 'climatesolution-48ea6.firebasestorage.app',
//     measurementId: 'G-J0ZTLEC3MT',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyCGIFLI-5fhYltT2XGkj9j1-SKmvgU90cU',
//     appId: '1:24961272906:android:1be00e735000bc6fcf2ab3',
//     messagingSenderId: '24961272906',
//     projectId: 'climatesolution-48ea6',
//     storageBucket: 'climatesolution-48ea6.firebasestorage.app',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyBLNW2tvFc7DkhUIpXcvNywp9kQsl5MR_w',
//     appId: '1:24961272906:ios:a4543cfbc72627bbcf2ab3',
//     messagingSenderId: '24961272906',
//     projectId: 'climatesolution-48ea6',
//     storageBucket: 'climatesolution-48ea6.firebasestorage.app',
//     iosBundleId: 'com.example.solution',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyBLNW2tvFc7DkhUIpXcvNywp9kQsl5MR_w',
//     appId: '1:24961272906:ios:a4543cfbc72627bbcf2ab3',
//     messagingSenderId: '24961272906',
//     projectId: 'climatesolution-48ea6',
//     storageBucket: 'climatesolution-48ea6.firebasestorage.app',
//     iosBundleId: 'com.example.solution',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyDB1eFVR_48DHgIBkkkgaO6GprIeE3V5ns',
//     appId: '1:24961272906:web:74ba39df20cff464cf2ab3',
//     messagingSenderId: '24961272906',
//     projectId: 'climatesolution-48ea6',
//     authDomain: 'climatesolution-48ea6.firebaseapp.com',
//     storageBucket: 'climatesolution-48ea6.firebasestorage.app',
//     measurementId: 'G-661HEJQ341',
//   );
// }
